In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

from scipy import sparse

import numpy as np
import math

from game import Game, Minus_Game
from agent import Agent, Minus_Agent

## Load and prepare Dataset

In [2]:
categories = ['alt.atheism', 'soc.religion.christian']
newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'), categories=categories)
newsgroups_test = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'), categories=categories)

In [3]:
# converting text to vectors
vectorizer = TfidfVectorizer()
vectors_train = vectorizer.fit_transform(newsgroups_train.data)
vectors_test = vectorizer.transform(newsgroups_test.data)

## Train Model

In [4]:
# build model
clf = MultinomialNB(alpha=.01)
clf.fit(vectors_train, newsgroups_train.target)
pred = clf.predict(vectors_test)

In [5]:
metrics.f1_score(newsgroups_test.target, pred, average='macro')

0.7948197892406187

In [6]:
pred

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,

In [7]:
np.asarray(vectors_test.todense())

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
clf.predict(vectors_test[0])

array([1], dtype=int64)

In [9]:
clf.predict_proba(vectors_test)

array([[4.79110000e-01, 5.20890000e-01],
       [3.27028433e-01, 6.72971567e-01],
       [9.99986356e-01, 1.36444254e-05],
       ...,
       [2.81025943e-01, 7.18974057e-01],
       [4.90392825e-04, 9.99509607e-01],
       [1.15744913e-02, 9.88425509e-01]])

In [10]:
clf.predict(vectors_test[0])

array([1], dtype=int64)

In [11]:
np.argmax(clf.predict_proba(vectors_test[0]))

1

In [12]:
clf.predict_proba(vectors_test[0])[0, 0]

0.4791099996266649

## Explain

In [13]:
idx = 0

In [14]:
sample = np.array(vectors_test[idx].todense())

In [15]:
sample

array([[0., 0., 0., ..., 0., 0., 0.]])

In [16]:
type(sample)

numpy.ndarray

In [17]:
vectorizer.inverse_transform(sample)

[array(['am', 'article', 'bertrand', 'copy', 'could', 'guy', 'me', 'not',
        'russell', 'the', 'who', 'why', 'wrote'], dtype='<U79')]

In [18]:
target_label = newsgroups_test.target[idx]

In [19]:
target_label

1

In [20]:
game = Minus_Game(sample, clf.predict_proba, target_label)

In [21]:
len(game.available_actions)

13

In [22]:
agent = Minus_Agent(game, c=math.sqrt(2))

In [23]:
agent.run()

2021-09-18 17:32:45,014 - agent - INFO - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-09-18 17:32:45,017 - agent - INFO - Round:	0
2021-09-18 17:32:45,018 - agent - INFO - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-09-18 17:32:46,372 - agent - INFO - Distribution stable after 	100 episodes


In [24]:
ranks_0, ranks_1, mask_0, mask_1 = agent.get_best_path()

In [25]:
vectorizer.inverse_transform(ranks_0)

[array(['bertrand'], dtype='<U79')]

In [26]:
sparse.csr_matrix(sample*mask_0)

<1x15698 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [27]:
clf.predict_proba(sample*mask_0)

array([[0.71991725, 0.28008275]])

In [28]:
game.is_done(sample*mask_0, 0)

True

In [29]:
a = agent.root.get_infor_of_edges()
a.columns = range(a.shape[1])
b = a.loc['N',:]>0

In [30]:
a.loc[:,b.values]

0          1         2          3          4   \
N                       5          5        41          5          5   
W                       0          0        41          0          0   
c                 1.41421    1.41421   1.41421    1.41421    1.41421   
Win rate                0          0         1          0          0   
Part2            0.960741   0.960741  0.335505   0.960741   0.960741   
Value             1.35869    1.35869   1.47448    1.35869    1.35869   
Original Value  0.0318362 -0.0020183  0.240807 -0.0102522 -0.0243102   
Game is done        False      False     False      False      False   

                      5           6            7          8           9   \
N                      5           5            5          5           5   
W                      0           0            0          0           0   
c                1.41421     1.41421      1.41421    1.41421     1.41421   
Win rate               0           0            0          0           0   
Part2           0.960741    0.960741     0.960741   0.960741    0.960741   
Value            1.35869     1.35869      1.35869    1.35869     1.35869   
Original Value -0.188855  0.00703365 -0.000316279 -0.0949387  0.00642465   
Game is done       False       False        False      False       False   

                       10          11          12  
N                       5           5           5  
W                       0           0           0  
c                 1.41421     1.41421     1.41421  
Win rate                0           0           0  
Part2            0.960741    0.960741    0.960741  
Value             1.35869     1.35869     1.35869  
Original Value  0.0106261 -0.00216097 -0.00841335  
Game is done        False       False       False